---
output:
  github_document:
    fig_width: 12
    fig_height: 10
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE, echo = FALSE}
library(magrittr)
```

# hrgraphsign
```
Simplifies analysis of hr-graph data based on a number of signatures
from this article: https://hbr.org/2018/11/better-people-analytics

```

## Installation
```
devtools::install_github("mrtnnrdlnd/hrgraphsign")
```

## Example

### Import Data

```{r, warning = FALSE, message = FALSE}
nodes <- readxl::read_excel("example/nodes.xlsx")
knitr::kable(nodes %>% head(5))
```

```{r, warning = FALSE, message = FALSE}
edges <- readxl::read_excel("example/edges.xlsx")
knitr::kable(edges %>% head(5))
```

### Create Graph

```{r, warning = FALSE, message = FALSE}
example_graph <- edges %>% 
  dplyr::select(FromID, ToID) %>%
  igraph::graph_from_data_frame(directed = FALSE, vertices = nodes) %>% 
  hrgraphsign::aggregate_edges()
```

### Ideation Signature
Predicts, according to the article, which employees will come up with good ideas
```{r, warning = FALSE, message = FALSE}
igraph::V(example_graph)$ideation <- hrgraphsign::ideation_signature(example_graph)
```

### Influence Signature
Predicts, according to the article, Which employees will change others’ behavior
```{r, warning = FALSE, message = FALSE}
igraph::V(example_graph)$influence <- hrgraphsign::influence_signature(example_graph)
```

### Display top 10 
```{r, warning = FALSE, message = FALSE}
knitr::kable(hrgraphsign::get_top_by_column(example_graph, column = "ideation", n = 10))
```

### Plot graph

```{r, warning = FALSE, message = FALSE}
set.seed(5)
layout1 <- igraph::layout.fruchterman.reingold(example_graph)
par(mfrow = c(1,2))
plot(example_graph,
     edge.width = igraph::E(example_graph)$weights,
     vertex.color = hrgraphsign::vertices_colors(example_graph, attribute = "department"),
     vertex.size = hrgraphsign::vertices_sizes(example_graph, attribute = "ideation"),
     main = "Ideation",
     layout = layout1
     )
plot(example_graph,
     edge.width = igraph::E(example_graph)$weights,
     vertex.color = hrgraphsign::vertices_colors(example_graph, attribute = "department"),
     vertex.size = hrgraphsign::vertices_sizes(example_graph, attribute = "influence"),
     main = "Influence",
     layout = layout1
)
```

### Plot friends_friends

```{r, warning = FALSE, message = FALSE}

par(mfrow = c(1,2))
subgraph <- hrgraphsign::friends_friends(example_graph, 13, 2)
set.seed(10)
layout2 <- igraph::layout.fruchterman.reingold(subgraph)
  plot(subgraph,
       edge.width = igraph::E(example_graph)$weights,
       vertex.color = hrgraphsign::vertices_colors(subgraph, attribute = "department"),
       vertex.size = hrgraphsign::vertices_sizes(subgraph, attribute = "ideation"),
       main = "Ideation",
       layout = layout2
  )
  plot(subgraph,
       edge.width = igraph::E(example_graph)$weights,
       vertex.color = hrgraphsign::vertices_colors(subgraph, attribute = "department"),
       vertex.size = hrgraphsign::vertices_sizes(subgraph, attribute = "influence"),
       main = "Influence",
       layout = layout2
  )
```
